pdf: install-config.tex
	xelatex install-config.tex
	xelatex install-config.tex
md: install-config.tex
	pandoc -o install-config.md install-config.tex
clean:
	rm -f *.lof *.lot *.aux *.out *.toc *.log *~
	rm -r auto
